// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NinjaManager.Domain.Data;

namespace NinjaManager.Domain.Migrations
{
  [DbContext(typeof(DatabaseContext))]
  [Migration("20201009123305_InitialCreate")]
  partial class InitialCreate
  {
    protected override void BuildTargetModel(ModelBuilder modelBuilder)
    {
#pragma warning disable 612, 618
      modelBuilder
          .HasAnnotation("ProductVersion", "3.1.8")
          .HasAnnotation("Relational:MaxIdentifierLength", 128)
          .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

      modelBuilder.Entity("NinjaManager.Domain.Models.Gear", b =>
          {
            b.Property<int>("Id")
                      .ValueGeneratedOnAdd()
                      .HasColumnType("int")
                      .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            b.Property<int>("Agility")
                      .HasColumnType("int");

            b.Property<int>("Intelligence")
                      .HasColumnType("int");

            b.Property<string>("Name")
                      .IsRequired()
                      .HasColumnType("varchar(100)")
                      .HasMaxLength(100);

            b.Property<int>("Price")
                      .HasColumnType("int");

            b.Property<string>("Slot")
                      .IsRequired()
                      .HasColumnType("nvarchar(max)");

            b.Property<int>("Strength")
                      .HasColumnType("int");

            b.HasKey("Id");

            b.HasIndex("Name")
                      .IsUnique();

            b.ToTable("gear");
          });

      modelBuilder.Entity("NinjaManager.Domain.Models.Ninja", b =>
          {
            b.Property<int>("Id")
                      .ValueGeneratedOnAdd()
                      .HasColumnType("int")
                      .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            b.Property<int>("Gold")
                      .HasColumnType("int");

            b.Property<string>("Name")
                      .IsRequired()
                      .HasColumnType("varchar(100)")
                      .HasMaxLength(100);

            b.HasKey("Id");

            b.HasIndex("Name")
                      .IsUnique();

            b.ToTable("ninja");
          });

      modelBuilder.Entity("NinjaManager.Domain.Models.NinjaGear", b =>
          {
            b.Property<int>("GearId")
                      .HasColumnType("int");

            b.Property<int>("NinjaId")
                      .HasColumnType("int");

            b.Property<int>("Price")
                      .HasColumnType("int");

            b.HasKey("GearId", "NinjaId");

            b.HasIndex("NinjaId");

            b.ToTable("ninja_gear");
          });

      modelBuilder.Entity("NinjaManager.Domain.Models.NinjaGear", b =>
          {
            b.HasOne("NinjaManager.Domain.Models.Gear", "Gear")
                      .WithMany("Ninjas")
                      .HasForeignKey("GearId")
                      .OnDelete(DeleteBehavior.Cascade)
                      .IsRequired();

            b.HasOne("NinjaManager.Domain.Models.Ninja", "Ninja")
                      .WithMany("Gear")
                      .HasForeignKey("NinjaId")
                      .OnDelete(DeleteBehavior.Cascade)
                      .IsRequired();
          });
#pragma warning restore 612, 618
    }
  }
}
